"""Adiciona campo RG ao usuário

Revision ID: 082ae1c5a5ae
Revises: 416a2523baa5
Create Date: 2025-08-06 11:08:32.824830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082ae1c5a5ae'
down_revision = '416a2523baa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rg', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('rg')

    # ### end Alembic commands ###
