"""Relaciona tabelas com Obra com nomes nas FK

Revision ID: 13faaa08e060
Revises: 
Create Date: 2025-07-30 09:19:57.259227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13faaa08e060'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento_vistoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('obra_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_agendamento_obra', 'obra', ['obra_id'], ['id'])

    with op.batch_alter_table('comunicacao_obra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('obra_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_comunicacao_obra', 'obra', ['obra_id'], ['id'])

    with op.batch_alter_table('imovel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('obra_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_imovel_obra', 'obra', ['obra_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('obra_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_obra', 'obra', ['obra_id'], ['id'])

    with op.batch_alter_table('vistoria_imovel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('obra_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_vistoria_obra', 'obra', ['obra_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vistoria_imovel', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vistoria_obra', type_='foreignkey')
        batch_op.drop_column('obra_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_obra', type_='foreignkey')
        batch_op.drop_column('obra_id')

    with op.batch_alter_table('imovel', schema=None) as batch_op:
        batch_op.drop_constraint('fk_imovel_obra', type_='foreignkey')
        batch_op.drop_column('obra_id')

    with op.batch_alter_table('comunicacao_obra', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comunicacao_obra', type_='foreignkey')
        batch_op.drop_column('obra_id')

    with op.batch_alter_table('agendamento_vistoria', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agendamento_obra', type_='foreignkey')
        batch_op.drop_column('obra_id')

    # ### end Alembic commands ###
