"""Adiciona campo uso na vistoria

Revision ID: 206f661568f7
Revises: 5c469f7884f1
Create Date: 2025-08-05 10:45:52.325669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206f661568f7'
down_revision = '5c469f7884f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vistoria_imovel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uso', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vistoria_imovel', schema=None) as batch_op:
        batch_op.drop_column('uso')

    # ### end Alembic commands ###
