"""Movendo bairro e numero para ComunicacaoObra

Revision ID: 2eedcab624c9
Revises: c268b75e9585
Create Date: 2025-08-03 20:45:26.209088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eedcab624c9'
down_revision = 'c268b75e9585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunicacao_obra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('numero', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunicacao_obra', schema=None) as batch_op:
        batch_op.drop_column('numero')
        batch_op.drop_column('bairro')

    # ### end Alembic commands ###
