"""add FotoVistoria

Revision ID: 393cf5910460
Revises: f71f8f2eff11
Create Date: 2025-07-31 10:12:31.272175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393cf5910460'
down_revision = 'f71f8f2eff11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto_vistoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('data_envio', sa.DateTime(), nullable=True))
        batch_op.drop_column('caminho')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto_vistoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caminho', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('data_envio')
        batch_op.drop_column('url')
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###
