"""Adiciona obra_id e usuario_nome à ComunicacaoObra

Revision ID: 3ee810038af9
Revises: 40702d955dac
Create Date: 2025-08-03 14:03:01.629816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee810038af9'
down_revision = '40702d955dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunicacao_obra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_nome', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunicacao_obra', schema=None) as batch_op:
        batch_op.drop_column('usuario_nome')

    # ### end Alembic commands ###
