"""Adiciona campo assinatura_base64 em VistoriaImovel

Revision ID: 416a2523baa5
Revises: 206f661568f7
Create Date: 2025-08-05 11:10:33.687110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416a2523baa5'
down_revision = '206f661568f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vistoria_imovel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assinatura_base64', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vistoria_imovel', schema=None) as batch_op:
        batch_op.drop_column('assinatura_base64')

    # ### end Alembic commands ###
