"""criação das tabelas com campos de vistoria completos

Revision ID: de36daae011c
Revises: 
Create Date: 2025-07-28 20:21:56.754507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de36daae011c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vistoria_imovel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_responsavel', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cpf_responsavel', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tipo_vinculo', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vistoria_imovel', schema=None) as batch_op:
        batch_op.drop_column('tipo_vinculo')
        batch_op.drop_column('cpf_responsavel')
        batch_op.drop_column('nome_responsavel')

    # ### end Alembic commands ###
