"""Adiciona campo nome ao User (nullable=True)

Revision ID: e7ce372355c1
Revises: 3ee810038af9
Create Date: 2025-08-03 17:07:10.951616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ce372355c1'
down_revision = '3ee810038af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_comunicacao_obra')
    with op.batch_alter_table('comunicacao_obra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_usuario_comunicacao', 'user', ['usuario_id'], ['id'])
        batch_op.drop_column('usuario_nome')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('nome')

    with op.batch_alter_table('comunicacao_obra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_nome', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_usuario_comunicacao', type_='foreignkey')
        batch_op.drop_column('usuario_id')

    op.create_table('_alembic_tmp_comunicacao_obra',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=20), nullable=True),
    sa.Column('endereco', sa.VARCHAR(length=255), nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('comunicado', sa.VARCHAR(length=20), nullable=True),
    sa.Column('economia', sa.VARCHAR(length=50), nullable=True),
    sa.Column('assinatura', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tipo_imovel', sa.VARCHAR(length=200), nullable=True),
    sa.Column('data_envio', sa.DATETIME(), nullable=True),
    sa.Column('obra_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['obra_id'], ['obra.id'], name=op.f('fk_comunicacao_obra')),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], name=op.f('fk_usuario_comunicacao')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
