"""add descricao to FotoVistoria

Revision ID: ecade2d77b2f
Revises: 393cf5910460
Create Date: 2025-07-31 11:01:31.547777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecade2d77b2f'
down_revision = '393cf5910460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto_vistoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto_vistoria', schema=None) as batch_op:
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###
