"""Alterar tipos de data e hora nas vistorias

Revision ID: f71f8f2eff11
Revises: 13faaa08e060
Create Date: 2025-07-30 13:50:32.880813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71f8f2eff11'
down_revision = '13faaa08e060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vistoria_imovel', schema=None) as batch_op:
        batch_op.alter_column('data_1',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('hora_1',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('data_2',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('hora_2',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('data_3',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('hora_3',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Time(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vistoria_imovel', schema=None) as batch_op:
        batch_op.alter_column('hora_3',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('data_3',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('hora_2',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('data_2',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('hora_1',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('data_1',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
