"""Adiciona comunicacao_id em VistoriaImovel

Revision ID: ff04c52c13d8
Revises: ecade2d77b2f
Create Date: 2025-08-01 12:19:38.531896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff04c52c13d8'
down_revision = 'ecade2d77b2f'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('vistoria_imovel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comunicacao_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_vistoria_comunicacao',     # ✅ Nome obrigatório da constraint
            'comunicacao_obra',
            ['comunicacao_id'],
            ['id']
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vistoria_imovel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('comunicacao_id')

    # ### end Alembic commands ###
